import React, { useEffect } from 'react';
import { InputField, CheckboxField, CollapsibleSection } from './UI';
import { calculateNut } from '../utils/helpers';

export const MachineDataForm = ({ data, onChange }) => {
    const handleFieldChange = (e) => {
        const { name, value } = e.target;
        const newData = { ...data, [name]: value };
        if(name === 'durchmesser_pumpe') newData.nut = calculateNut(value);
        if(name === 'durchmesser_motor') newData.nut_motor = calculateNut(value);
        onChange(newData);
    };

    return (
        <div className="animate-in pb-24">
            <CollapsibleSection title="Allgemeine Informationen">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><InputField label="Werk" name="werk" value={data.werk} onChange={handleFieldChange} placeholder="z.B. Clariant" /><InputField label="Anlage" name="anlage" value={data.anlage} onChange={handleFieldChange} placeholder="z.B. PZP" /><InputField label="Position" name="position" value={data.position} onChange={handleFieldChange} placeholder="z.B. 7595" /><InputField label="Technischer Platz" name="tech_platz" value={data.tech_platz} onChange={handleFieldChange} placeholder="z.B. VER-0114-0000/XX" /></div>
            </CollapsibleSection>
            <CollapsibleSection title="Ansprechpartner">
                <div className="border-b border-slate-200 pb-2 mb-4"><h4 className="font-bold text-slate-700 flex items-center gap-2 text-sm uppercase tracking-wide"><span className="w-2 h-2 bg-blue-500 rounded-full"></span> Kunde (Betrieb)</h4></div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6"><InputField label="Betriebsingenieur" name="betriebsingenieur" value={data.betriebsingenieur} onChange={handleFieldChange} /><InputField label="Telefon" name="telefon" value={data.telefon} onChange={handleFieldChange} /><InputField label="E-Mail" name="mail" value={data.mail} onChange={handleFieldChange} /></div>
                <div className="border-b border-slate-200 pb-2 mb-4"><h4 className="font-bold text-slate-700 flex items-center gap-2 text-sm uppercase tracking-wide"><span className="w-2 h-2 bg-green-500 rounded-full"></span> Auftragnehmer</h4></div>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><InputField label="Sachbearbeiter" name="ync_bearbeiter" value={data.ync_bearbeiter} onChange={handleFieldChange} /><InputField label="Telefon" name="ync_telefon" value={data.ync_telefon} onChange={handleFieldChange} /><InputField label="E-Mail" name="ync_mail" value={data.ync_mail} onChange={handleFieldChange} /></div>
            </CollapsibleSection>
            <CollapsibleSection title="Pumpendaten">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><InputField label="Pumpen-Nr." name="nummer_pumpe" value={data.nummer_pumpe} onChange={handleFieldChange} required /><InputField label="Pumpenhersteller" name="hersteller" value={data.hersteller} onChange={handleFieldChange} list={ (window.maschinenConfig && window.maschinenConfig.hersteller) ? window.maschinenConfig.hersteller : ["RICHTER", "KSB", "Klaus Union"] } /><InputField label="Aggregatbezeichnung" name="bezeichnung" value={data.bezeichnung} onChange={handleFieldChange} /><InputField label="Pumpentyp" name="typ" value={data.typ} onChange={handleFieldChange} /><InputField label="Pumpengröße" name="groesse" value={data.groesse} onChange={handleFieldChange} /><InputField label="Saugstutzen" name="saugseite" value={data.saugseite} onChange={handleFieldChange} /><InputField label="Druckstutzen" name="druckseite" value={data.druckseite} onChange={handleFieldChange} /><InputField label="Wellendurchmesser [mm]" name="durchmesser_pumpe" value={data.durchmesser_pumpe} onChange={handleFieldChange} /><InputField label="Nut [mm]" name="nut" value={data.nut} onChange={handleFieldChange} placeholder="Auto-Berechnung" /><InputField label="Werkstoff" name="werkstoff" value={data.werkstoff} onChange={handleFieldChange} /><InputField label="Laufrad Ø [mm]" name="laufrad_durchmesser" value={data.laufrad_durchmesser} onChange={handleFieldChange} /><InputField label="Wellenabdichtung" name="dichtung_pumpe" value={data.dichtung_pumpe} onChange={handleFieldChange} list={ (window.dichtungConfig && window.dichtungConfig.art) ? window.dichtungConfig.art : ["Packung", "hermetisch"] } /><InputField label="Spitzenhöhe [mm]" name="hoehe_pumpe" value={data.hoehe_pumpe} onChange={handleFieldChange} /><div className="md:col-span-3 mt-2 mb-1 border-b border-slate-200"><h4 className="font-bold text-slate-500 text-xs uppercase">ATEX - Pumpe</h4></div><InputField label="Zone" name="zone" value={data.zone} onChange={handleFieldChange} list={ (window.zoneConfig && window.zoneConfig.zone) ? window.zoneConfig.zone : ["II1G", "II2G"] } /><InputField label="Temperaturklasse" name="temp_klasse" value={data.temp_klasse} onChange={handleFieldChange} list={ (window.tempConfig && window.tempConfig.temp) ? window.tempConfig.temp : ["T1", "T2"] } /><InputField label="Gruppe" name="gruppe" value={data.gruppe} onChange={handleFieldChange} list={ (window.gruppeConfig && window.gruppeConfig.gruppe) ? window.gruppeConfig.gruppe : ["IIA", "IIB"] } /></div>
                <div className="mt-4"><label className="block text-sm font-medium text-slate-700 mb-1">Bemerkungen</label><textarea name="bemerkung_pumpe" value={data.bemerkung_pumpe} onChange={handleFieldChange} rows="3" className="w-full p-2.5 border border-slate-300 bg-white rounded-lg outline-none focus:ring-2 focus:ring-blue-500" /></div>
            </CollapsibleSection>
            <CollapsibleSection title="Motordaten">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><InputField label="Motoren-Nr." name="nummer_motor" value={data.nummer_motor} onChange={handleFieldChange} /><InputField label="Motorgröße" name="groesse_motor" value={data.groesse_motor} onChange={handleFieldChange} /><InputField label="Leistung [kW]" name="leistung" value={data.leistung} onChange={handleFieldChange} /><InputField label="Drehzahl [1/min]" name="drehzahl" value={data.drehzahl} onChange={handleFieldChange} /><InputField label="Spitzenhöhe [mm]" name="hoehe_motor" value={data.hoehe_motor} onChange={handleFieldChange} /><InputField label="Wellendurchmesser [mm]" name="durchmesser_motor" value={data.durchmesser_motor} onChange={handleFieldChange} /><InputField label="Nut [mm]" name="nut_motor" value={data.nut_motor} onChange={handleFieldChange} placeholder="Auto-Berechnung" /><InputField label="Bauform" name="bauform" value={data.bauform} onChange={handleFieldChange} /><div className="md:col-span-3 mt-2 mb-1 border-b border-slate-200"><h4 className="font-bold text-slate-500 text-xs uppercase">ATEX - Motor</h4></div><InputField label="Zone" name="zone_motor" value={data.zone_motor} onChange={handleFieldChange} list={ (window.zoneConfig && window.zoneConfig.zone) ? window.zoneConfig.zone : ["II1G", "II2G"] } /><InputField label="Temperaturklasse" name="temp_klasse_motor" value={data.temp_klasse_motor} onChange={handleFieldChange} list={ (window.tempConfig && window.tempConfig.temp) ? window.tempConfig.temp : ["T1", "T2"] } /><InputField label="Gruppe" name="gruppe_motor" value={data.gruppe_motor} onChange={handleFieldChange} list={ (window.gruppeConfig && window.gruppeConfig.gruppe) ? window.gruppeConfig.gruppe : ["IIA", "IIB"] } /><InputField label="Zündschutzart" name="zuendschutz" value={data.zuendschutz} onChange={handleFieldChange} list={ (window.zuendConfig && window.zuendConfig.zuend) ? window.zuendConfig.zuend : ["II1G", "II2G"] } /></div>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4"><InputField label="Motor angefordert am" name="motor_angefordert" type="date" value={data.motor_angefordert} onChange={handleFieldChange} /><InputField label="Liefertermin" name="liefertermin" type="date" value={data.liefertermin} onChange={handleFieldChange} /></div>   
            </CollapsibleSection>
            <CollapsibleSection title="Peripherie & Abschluss">
                 <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><InputField label="Grundplatte" name="grundplatte" value={data.grundplatte} onChange={handleFieldChange} /><InputField label="Kupplung" name="kupplung" value={data.kupplung} onChange={handleFieldChange} /><InputField label="Kupplungsschutz" name="schutz" value={data.schutz} onChange={handleFieldChange} /><InputField label="Pumpen-Unterlagen" name="pumpe_unterlage" value={data.pumpe_unterlage} onChange={handleFieldChange} /><InputField label="Motor-Unterlagen" name="motor_unterlage" value={data.motor_unterlage} onChange={handleFieldChange} /></div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 border-t border-b border-slate-200 py-2 my-4"><CheckboxField label="Mit Schwingschienen" name="schwingschienen" value={data.schwingschienen} onChange={handleFieldChange} /><CheckboxField label="Überstand erlaubt" name="ueberstand" value={data.ueberstand} onChange={handleFieldChange} /><CheckboxField label="mit Stützen" name="stuetzen" value={data.stuetzen} onChange={handleFieldChange} /><CheckboxField label="Grundplatte verschraubt" name="verschraubt" value={data.verschraubt} onChange={handleFieldChange} /></div>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><InputField label="Bestell-Nr." name="bestellung" value={data.bestellung} onChange={handleFieldChange} /><InputField label="Auftrag" name="auftrag" value={data.auftrag} onChange={handleFieldChange} /></div>
                <div className="mt-4 mb-4"><label className="block text-sm font-medium text-slate-700 mb-1">Bemerkungen zur Bestellung</label><textarea name="bemerkung_bestellung" value={data.bemerkung_bestellung} onChange={handleFieldChange} rows="3" className="w-full p-2.5 border border-slate-300 bg-white rounded-lg outline-none focus:ring-2 focus:ring-blue-500" /></div>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><InputField label="Wunschtermin" name="wunschtermin" type="date" value={data.wunschtermin} onChange={handleFieldChange} /><InputField label="Aussteller" name="aussteller" value={data.aussteller} onChange={handleFieldChange} /><InputField label="Fertigstellung am" name="fertigstellung" type="date" value={data.fertigstellung} onChange={handleFieldChange} /><InputField label="Geprüft" name="geprueft" value={data.geprueft} onChange={handleFieldChange} /></div>
                 <p className="text-sm text-orange-600 mt-4 flex items-start gap-2 border border-orange-200 bg-orange-50 p-3 rounded-lg"><Icons.AlertTriangle /> Hinweis: Eine Änderung der Förderhöhe kann Auswirkungen auf den Absicherungsdruck von Druckbehältern und Rohrleitungen haben.</p>
            </CollapsibleSection>
        </div>
    );
};

export const TechnicalDrawingForm = ({ data, onChange }) => {
    const handleFieldChange = (e) => onChange({ ...data, [e.target.name]: e.target.value });
    return (
        <div className="p-6 bg-white rounded-xl shadow-sm border border-slate-200">
             <InputField label="Bezeichnung" name="drawingTitle" value={data.drawingTitle} onChange={handleFieldChange} required />
             <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-4">
                <InputField label="L Gesamt" name="l_total" value={data.l_total} onChange={handleFieldChange} />
                <InputField label="H Gesamt" name="h_total" value={data.h_total} onChange={handleFieldChange} />
                <InputField label="Breite" name="w_base" value={data.w_base} onChange={handleFieldChange} />
             </div>
        </div>
    );
};
